[gcp_service_account]
type = "service_account"
project_id = "msp-sops"
private_key_id = "42890e024e806e0301c882e51753ccfc962be1f8"
private_key = "-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDQlHFaOMG6pcfW
ArMNEOQUxvD5Obeo5zRZoo1gwemYt2B8ajK9u4cG0HPEN2bAkyjJZxv2OJgmUEUc
0Fl0owu5u1sGbBFP1KlmXdhIbsD8N+f8HBCiaBNPJwW7F0y8jFt5webuxnfSclLW
94VawlKre02YEwops68+WlxwzE18UpK4C1gGliyAxphUDIUXgrKf7q/dL1v33om7
UmHhZbbYy8niKXW3ZEkXRoCYaKtZSgZsOtFQcu91yjK24CGJfVNFl2JpsAJU08BU
SEFCFzAw7htT3CI7KTJGlzet0h8JOZPdBypT/4QJ1LZBU21omCqHaQvPH096kI5H
jzomYQ29AgMBAAECggEAIdLIlORaSg2jG8nBRk+kZNgj8I5TAZFIlHZ/LZ8UZd7q
xxIjm0/jJBA+jaWcRIM4nHxbdPCVf7UJmBQTRY5BEwPWTXLN1d+6/q4eKhTHt77L
ID9e1S9CXlYKIF41Y+fw14xBihvmB1rhoxltZxvW8xbiLNR9k+ie9OILVoFS2WNx
dbmj8VUC7zlW6NiGkyGGQItSAXOZDxvy4d/ZaLLlGxWLPL09SgyPvofnEAUfepoH
p9P6EgkdhlXt4O+0XjikrzbXBn8bTXbUGsCoIpxm+lF1/59FODTecvDlGiIA891P
rUqlm5VE4tGK4zx9VOGWJVweUUSj0z5XC66Fs2fvIQKBgQD0lrS4R/B98FlAlY/O
nJckoJB1FYcMaDTEJC6xwcGazbY344n8IOow10zKHbQ+4G2aRH2ZOK+ug0SY5A51
k1MplWy2rswTWzg/m9nLE0SAVpymEAclZfM8CENIC/bBghzMQPIXHw6DtjzTiV8L
pD6eK6zVEYYtTrz1Axnn9HIN0QKBgQDaT6h14TDuSNRj0eqCh5aY99nKRKyM0z49
v3IjIft7qbP+BkWHKq9JePDrFAwhOfdDSuezmBC7lTRPKiM9a+WPq4dxFB9y5+AL
euETw1n6Qbgmy3rHuv0GbGaag9ooqzoIvg0g1dfaiqxbGAjLlCBvFILnNArH0XeA
aFkzXRKgLQKBgQC1xjM1KbHfxvpt9zlTMilZ/UKe4Yrme6OLieByFy+NnwinbKGm
Ecg62Cenpn/Iov6RwgkeEHTwW3plrkfYtc7+fqC2/B2K3SZmj6tDM2SbhMMS36KP
9r7YhMOMDegrVEmWu0WwTVJ6LLvz8ooCmuQ2pPrjtwxjK7te1BkyvAbvoQKBgBjB
v9DeYLYk/DD1tSpoRePC96fAcfDmY8CM3Vyuld5IOGkuPOQ/KvGiDXAbLeT2tduj
uvLa48rh+LShiq2Edtv8D7f7GDXnpbinjq63EJUYrtF3cc0En30C/f+3xB2ojURA
iSyYE4ps/261IwozGhp+sPmXJUHTt0GQk80HWP1hAoGAf6TdZi7jhAMesa5w8axu
XoRC2Vh4+iGZjmMgMSD7V8QukzhcNEOHWI+/3347cpLV+TjNE30iLfIOZamj1DQy
nyw9NEv83os7r/84oKmZxwasUGege2d7IUGK5+IXzitoZsNgq8jxFl/jYnIxkKAO
3tG5IFeU/rfqTfFdNy8cn5o=
-----END PRIVATE KEY-----
"
client_email = "msp-sops@msp-sops.iam.gserviceaccount.com"
client_id = "114544788867347993995"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/msp-sops%40msp-sops.iam.gserviceaccount.com"
universe_domain = "googleapis.com"